### ISSUE TITLE
Does v3.0.0-rc.3 break client definitions in `~/sanity/client.ts`?

### ISSUE THREAD

**Issue by bradymwilliams** [SimeonGriggs/remix-sanity-studio-v3#22]
Hey Simeon, this repo has been gold as far as real-world v3 examples go, much appreciated.

### Question
Does v3.0.0-rc.3 break client definitions in `~/sanity/client.ts`?

### Context

I'm finding that after updating to the latest RC getting infinite hangs on the client in app that I'm not when running the same query in a simple script ran with node.

Thanks!

**Comment by bradymwilliams** [comment]
Welp, it turned out to be an issue where the studio websocket wouldn't connect due to React Strict mode.

**Comment by SimeonGriggs** [comment]
Can't reproduce the errors, have you tried with the latest `^3.0.0` release?

**Comment by bradymwilliams** [comment]
I got the error copying this implementation into a project started with the indie stack. 

Oddly enough I migrated to a different stack and the errorless hangs have gone away. Very strange.
