### ISSUE TITLE
A version for Cloudflare Pages 

### ISSUE THREAD

**Issue by IshanKBG** [SimeonGriggs/remix-sanity-studio-v3#23]
Can you make a version  for cloudflare pages as well using remix and sanity v3.
I tried porting this to cloudflare and used their method for streaming as well but I am getting tons of error so could you please make a version  for cloudflare pages as well?
It would be really helpful to run Sanity Studio from the edge

**Comment by SimeonGriggs** [comment]
Try installing the `esm` tagged version of Sanity Client. It's a prerelease version which supports more environments.

```
npm install @sanity/client@esm
```

**Comment by IshanKBG** [comment]
Ok I will try thanks

**Comment by IshanKBG** [comment]
@SimeonGriggs it looks another issue is that studio uses styled components and that is not supported in workers runtime thus causing errors
